AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  InstanceType:
    Description: Ec2 Instance types
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t3.nano
      - t3.small

Resources:
    EC2Instance:
       Type: AWS::EC2::Instance
       Properties:
          InstanceType: t2.micro
          ImageId: ami-08d4ac5b634553e16
          SecurityGroups:
            - !Ref InstanceSecurityGroup

    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable SSH access via port 22
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
  
Outputs:
  InstanceId:
    Description: Instance of the EC2 Instance
    Value: !Ref EC2Instance
  PublicDNS:
     Description: Public DNSName of the EC2 Instance
     Value: !GetAtt
              - EC2Instance
              - PublicDnsName
  PublicIP:
    Description: Public Ip of this EC2 Instance 
    Value: !GetAtt
             - EC2Instance
             - PublicIp